# Problem 1
General CSS codes.

## a) Show that any distance 3 CSS code can correct any single qubit error and a two-qubit error composed of one Z and one X.

CSS codes are defined by two classical codes: C1 and C2. C1 is used to correct for X errors, and is represented with the classical code's parity check matrix is used, substituting each 1 for a Z gate, and each 0 for an I gate. Similarly, C2 is used to correct for Z errors, where the classical code's parity check matrix is used by substituting each 1 for an X gate and each 0 for an I gate.

Since this code is made up of two codes, each which independently correct for a single type of {X,Z} errors, and we know that the classical codes that underpin each are complete, we know that we can correct any single qubit X or Z error with these two codes simeltaneously, and by extension, any single qubit Y error (since it is a single C and Z on the same qubit).

Additionally, since we know that one code is a subset of the other, we can correct any 2-qubit error that is made up of exactly one X and Z. This means the total number of errors that can be corrected are any single qubit error and one qubit error composed of one Z and one X.

## b) For any distance 2k+1 CSS code, describe the set of errors that can be corrected.

Going off of the previous question's logic, any 2k+1 CSS code will be made up of two classical codes, C1 and C2, each with distance k. This means that each of these classical codes could correct k separate errors of their respective X or Z type, and therefore together they can correct k one-qubit errors of any type (X, Y, or Z). Additionally, since one code is a subset of the other, we can correct one more two-qubit error, assuming it is made up of one X gate and one Z gate.

## c) Specific codes can correct more errors. Show the Steane [7,1,3] code can only correct the minimal number of errors. Identify the extra errors that the Shor [9,1,3] code can correct.

# Problem 2
### 16 Qubit Shor Code

Consdier the 16 qubit Shor code

Let's label each qubit by coordinates i,j ona grid with i and j from 0 to 3

The Z stabilizers are  Zi,jZi,j+1 are for i=0 to 3 and j=0 to 2

The X stabilizers are Xi,0Xi+1,0Xi,1Xi+1,1Xi,2Xi+1,2Xi,3Xi+1,3 for i=0 to 2

## a) Write down the stabilizers in the binary form.

Using the notation where each qubit is indexed with j as the two most signifigant bits and i as the two least signifigant bits, i.e. qubit 6 (binary: 0110) corresponds to i = 10 and j = 01.

In [13]:
z_stabilizers = []
for j in range(0,3):
    for i in range(0,4):
        newline = ""
        for b in range(0,16):
            newline += "1" if (b == (4*j+i)) or (b == (4*(j+1)+i)) else "0"
        z_stabilizers.append(newline)
print("Z Stabilizers:")
for stab in z_stabilizers:    
    print(stab)

x_stabilizers = []
for i in range(0,3):
    newline = ""
    for b in range(0,16):
        newline += "1" if (b == i) or\
        (b == i+1) or (b == i+4) or\
        (b == i+5) or (b == i+8) or\
        (b == i+9) or (b == i+12) or\
        (b == i+13) else "0"
    x_stabilizers.append(newline)
print("\nX Stabilizers:")
for stab in x_stabilizers:    
    print(stab)

Z Stabilizers:
1000100000000000
0100010000000000
0010001000000000
0001000100000000
0000100010000000
0000010001000000
0000001000100000
0000000100010000
0000000010001000
0000000001000100
0000000000100010
0000000000010001

X Stabilizers:
1100110011001100
0110011001100110
0011001100110011


## b) Identify the classical codes C1 and C2. (Find H and G. Does not need to be in standard form.)

Since the stabilizers are constructed using the classical partiy check matricies for C1 and C2, we can reconstruct these H and G matricies by looking at the Z and X stabilizers. 

The X stabilizers are made from the matrix H(C2^⊥)=G(C2)^T and the Z stabilizers are made from the H(C1) matrix.

In [35]:
import numpy as np
import cmath

HC1 = np.array([
    [1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
    [0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
    [0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0],
    [0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0],
    [0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0],
    [0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0],
    [0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0],
    [0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0],
    [0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0],
    [0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0],
    [0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0],
    [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1]
])

GC2 = np.array([
    [1,0,0],
    [1,1,0],
    [0,1,1],
    [0,0,1],
    [1,0,0],
    [1,1,0],
    [0,1,1],
    [0,0,1],
    [1,0,0],
    [1,1,0],
    [0,1,1],
    [0,0,1],
    [1,0,0],
    [1,1,0],
    [0,1,1],
    [0,0,1]
])

print("H(C1):")
print(HC1)
print("G(C2):")
print(GC2)

H(C1):
[[1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1]]
G(C2):
[[1 0 0]
 [1 1 0]
 [0 1 1]
 [0 0 1]
 [1 0 0]
 [1 1 0]
 [0 1 1]
 [0 0 1]
 [1 0 0]
 [1 1 0]
 [0 1 1]
 [0 0 1]
 [1 0 0]
 [1 1 0]
 [0 1 1]
 [0 0 1]]


Now, we can turn these matricies into canonical form to easily create the missing H and G matricies. This is done for the H matrix by taking linearily independent combinations of rows, and for the G matrix by taking linearily independent combinations of columns.

In [36]:
# Put H into canonical form by taking linearly independent combinations of rows
for i in range(11,7,-1):
    HC1[i] = np.remainder((HC1[i]+HC1[i-4]),2)
    HC1[i] = np.remainder((HC1[i]+HC1[i-8]),2)
for i in range(7,3,-1):
    HC1[i] = np.remainder((HC1[i]+HC1[i-4]),2)
print("H(C1) in canonical form:")
print(HC1)

# Put G into canonical form by taking linearly independent combinations of columns
GC2t = np.transpose(GC2)
GC2t[0] = np.remainder((GC2t[0]+GC2t[1]),2)
GC2t[0] = np.remainder((GC2t[0]+GC2t[2]),2)
GC2t[1] = np.remainder((GC2t[1]+GC2t[2]),2)

print("G(C2) in canonical form:")
print(np.transpose(GC2t))


H(C1) in canonical form:
[[1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1]]
G(C2) in canonical form:
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 1]]


From these, we can use the fact that H = [[A I_{nxn}] and G = [[I{mxm}],[A]] To create the missing matricies.

In [39]:
HC2 = np.array([
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
    [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
    [1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
    [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
    [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,],
    [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,],
    [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,],
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,],
    [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,],
])

GC1 = np.array([
    [1, 0, 0, 0,],
    [0, 1, 0, 0,],
    [0, 0, 1, 0,],
    [0, 0, 0, 1,],
    [1, 0, 0, 0,],
    [0, 1, 0, 0,],
    [0, 0, 1, 0,],
    [0, 0, 0, 1,],
    [1, 0, 0, 0,],
    [0, 1, 0, 0,],
    [0, 0, 1, 0,],
    [0, 0, 0, 1,],
    [1, 0, 0, 0,],
    [0, 1, 0, 0,],
    [0, 0, 1, 0,],
    [0, 0, 0, 1,],
])

print("H(C2):")
print(HC2)
print("G(C1):")
print(GC1)

H(C2):
[[1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]
G(C1):
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## c) Show that C2 is in C1

In [55]:
GC2prime = np.transpose(GC1)
GC2prime[0] = np.remainder((GC2prime[0]+GC2prime[3]),2)
GC2prime[1] = np.remainder((GC2prime[1]+GC2prime[3]),2)
GC2prime[2] = np.remainder((GC2prime[2]+GC2prime[3]),2)
GC2prime = np.delete(GC2prime,3,0)
print("G(C2)':")
print(np.transpose(GC2prime))


G(C2)':
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 1]]


C2 can be expressed as a linear combination of colums of C1 like so:

C2 = [ C1_1+C1_4 | C1_2+C1_4 | C1_3+C1_4  ]

Therefore, C2 is in C1.

## d) What is the distance and number of encoded bits for C2 and C1?

The number of encoded bits is equal to the number of rows in the generator matrix. Since G(C1) is a 16x4 matrix, it encodes 4-bit messages into 16 bits. Since G(C2) is a 16x3 matrix, it encodes 3-bit messages into 16 bits.

The distance of a linear code is equal to the minimum number of linearily dependent columns of H. Since we represent H in canonical form, we know that it is comprised of k columns from the A matrix, and the rest of the columns are an mxm identity matrix. This means that every column of the A matrix is linearily dependent on the identity matrix, and so the minimum number of linearily dependent columns of H must be k, and therefore the distance of the code is k. For C1, the distance = k = 4 and for C2, the distance = k = 3.

## e) What is the disance and number of encoded qubits for the quantum code?

The number of encoded qubits of the quantum code is k_{C1}-k_{C2} = 4-3 = 1.

The distance of a quantum code is equal to 2t+1, where t is the number of errors that can be corrected by C1 and C2. We know k for each of the codes, and we can use the relation k=t-m to find n, where m is the number of rows of the A matrix that are linearily independent. For C1, m is 4, and therefore t = k-m = 4-4 = 0. For C2, m is 3, and therefore t = k-m = 3-3 = 0, which matches the t for C1. Therfore, for the quantum code, the distance = 2*(0) + 1 = 1.

## f) Find minimal weight logical operators X and Z. 

Focusing on the logical Z gate, we can reduce the weight by changing some Z's into I's. Since we need the logical operator to still commute with all elements of the generator, we can see that if we just leave one Z in the first and fifth qubit positions like so:

|Z>_L = Z_1 Z_5

Then we commute with all Z stabilizers except 0000100010000000. So, to fix this issue, we add another Z gate on the 9th position:

|Z>_L = Z_1 Z_5 Z_9

Now we commute with all Z stabilizers except 0000000010001000. So, we can add another Z gate on the 13th position:

|Z>_L = Z_1 Z_5 Z_9 Z_13

And now we commute with all Z stabilizers.

We can also see that this logical Z operator commutes with all X stabilizers, since only the first X stabilizer has any non-identity gates on the positions where we have Z gates in the logical Z:

1000100010001000 (logical Z)

1100110011001100 (1st X stabilizer)

And, there are an even number of X and Z acting on one another, so we know that these commute. Therefore, the smallest weight logical Z is given by:

|Z>_L = Z_1 Z_5 Z_9 Z_13

To create the smallest weight logical X, we can use the same process of creating the logical Z and the knowledge that logical X must anticommute with logical Z. We can try fillilng in the 'opposite' positions from the logical Z:

|X>_L = X_2 X_3 X_4 X_6 X_7 X_8 X_10 X_11 X_12 X_14 X_15 X_16

Which commutes with all Z and X stabilizers following the same steps as when we created logical Z.